spring.application.name=finance-backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/finance_saas?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d3e6900f6b4df3d08e5c8e441f7155
jwt.expiration=86400000
